name: universal_html
version: 2.1.0
description:
  A 'dart:html' that works in all platforms, including Flutter and server-side.
  Eases cross-platform development and HTML / XML processing.
homepage: https://github.com/dint-dev/universal_html

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:


  async: ^2.11.0
  csslib: ^0.17.2
  charcode: ^1.3.1
  collection: ^1.17.1
  html: ^0.15.2
  meta: ^1.3.0
  source_span: ^1.8.0
  typed_data: ^1.3.1
  universal_io: ^2.2.0
  

dev_dependencies:
  lints: ^2.0.1
  stream_channel: ^2.1.0
  test: ^1.23.0
