name: Dart CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
      - run: flutter --version
      - name: Install dependencies (Dart)
        run: dart pub get
      - name: Install dependencies (Flutter)
        run: flutter pub get
        working-directory: test_in_flutter
      - name: Run tests (Dart)
        run: dart test --platform=vm
      - name: Run tests (Flutter)
        run: flutter test
        working-directory: test_in_flutter